# Generated by Django 3.2.2 on 2024-09-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0002_auto_20240902_2057'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_available', models.IntegerField()),
                ('total_unavailable', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(default='', max_length=300)),
                ('sub_category', models.CharField(default='', max_length=300)),
                ('post', models.CharField(max_length=100000)),
                ('required_experience', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.CharField(max_length=300)),
                ('job_url', models.CharField(max_length=1000)),
                ('reviewed', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('unavailable_date', models.DateTimeField(blank=True, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('in_office', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='companies.company')),
                ('location', models.ManyToManyField(related_name='locations', through='jobs.JobLocation', to='locations.Locations')),
                ('required_skills', models.ManyToManyField(related_name='skills', to='skills.Skills')),
            ],
            options={
                'unique_together': {('job_id', 'company')},
            },
        ),
        migrations.AddField(
            model_name='joblocation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locations'),
        ),
        migrations.AddIndex(
            model_name='joblocation',
            index=models.Index(fields=['job', 'location'], name='jobs_jobloc_job_id_4dacea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='joblocation',
            unique_together={('job', 'location')},
        ),
    ]
